// 全局状态
export const CHANGE_HAS_PULL_DATA_STATUS = 'CHANGE_HAS_PULL_DATA_STATUS';

// 登陆状态
export const CHANGE_USER_LOGIN_STATUS = 'CHANGE_USER_LOGIN_STATUS';
export const CHANGE_ADMIN_LOGIN_STATUS = 'CHANGE_ADMIN_LOGIN_STATUS';

// 前后台导航栏
export const CHANGE_MENU_KEY = 'CHANGE_MENU_KEY';
export const CHANGE_TABBAR_KEY = 'CHANGE_TABBAR_KEY';

// 存储用户信息
export const SAVE_USERINFO = 'SAVE_USERINFO';
